2020-11-22 01:06:17,931 INFO: Microblog startup [in /home/bingo/snap/code/git/microblog/app/__init__.py:48]
2020-11-22 01:12:03,815 INFO: Microblog startup [in /home/bingo/snap/code/git/microblog/app/__init__.py:48]
2020-11-22 01:15:10,830 ERROR: Exception on /register [POST] [in /home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bingo/snap/code/git/microblog/app/routes.py", line 65, in register
    if form.validate_on_submit():
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/bingo/snap/code/git/microblog/app/forms.py", line 25, in validate_username
    user = User.query.filter_by(username=username.data).first()
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/bingo/snap/code/git/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('Bingo', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-11-22 01:15:30,520 INFO: Microblog startup [in /home/bingo/snap/code/git/microblog/app/__init__.py:48]
